simphony/simphony-remote

tests/docker/test_async_docker_client.py

Fixes a warning due to a python request resource leak (from connectionpool
being GC before being cleaned up). This seems to be a request issue and I am
unsure we can do anything on our side. This PR simply silences the warning.
See https://github.com/kennethreitz/requests/issues/1882
for details about the issue itself.

Silence warning for resource leak

---

remoteappmanager/docker/container_manager.py
remoteappmanager/handlers/home_handler.py
tests/docker/test_container_manager.py

The checking for whether a volume source path exists should occur in the ContainerManager._start_container
Refactoring following #2 
This simplifies HomeHandler and makes it easier to test.

Check if volume source exists in ContainerManager

---

remoteappmanager/handlers/home_handler.py
remoteappmanager/templates/home.html

Provide part of #6 
- When a container fails to start (timeout error, runtime error...), a user-facing error message would be shown above the list of application with a reference number
- the reference number is printed to the log, make support easier
Limitation:
- If the user starts two applications at roughly the same time and both of them fail to start, only one of the error messages would be displayed
- Issue #14 
- Issue #15

Display error message at top of page when container fails to start

---

remoteappmanager/docker/container.py
remoteappmanager/docker/container_manager.py
tests/docker/test_container.py
tests/test_application.py

Passes an appropriate hex string to identify the container, instead of the container ID.
Requires appropriate change in the containers.

Replaced URL identifier from container id to uuid

---

remoteappmanager/docker/container.py
remoteappmanager/docker/container_manager.py
remoteappmanager/handlers/home_handler.py
tests/docker/test_container.py
tests/docker/test_container_manager.py
tests/utils.py

Fixes #14 #15 and provides #6 
- `ContainerManager.containers_for_image` returns a list of Container (as before) using docker Client API instead of the cached dictionary
- Refactor the error message for `HomeHandler._actionhandler_*` to `HomeHandler.post`
- Always clean up started container in something fails in _actionhandler

Feature: UI reaction to failure to start containers

---

remoteappmanager/application.py
remoteappmanager/db/orm.py
remoteappmanager/handlers/home_handler.py
remoteappmanager/user.py
tests/db/abc_test_interfaces.py
tests/db/test_interfaces.py
tests/db/test_orm.py

Depends on #47 
the `remoteappmanager.db` is now an instance of `orm.AccountingInterface` which subclass `ABCAccounting`
Note: AccountingInterface <--- I am not sold on this name :(

Feature adapt database interface

---

remoteappmanager/handlers/base_handler.py
remoteappmanager/services/hub.py
tests/handlers/test_home_handler.py
tests/services/test_hub.py

`verify_token` would return a dict containing the user data from jupyterhub and the remoteappmanager would further verify the data.  The dictionary is empty if authentication/authorisation fails.
HTTPError is not raised, but in the future we may want to introduce the HTTPError back again for better error message on the user's end.

verify_token always return a dict and not raise an HTTPError

---

remoteappmanager/cli/remoteappdb/__main__.py
tests/cli/test_remoteappdb.py

Provides for #58 
Also introduced `click.testing.CliRunner` in the tests and `RemoteAppDBContext` in remoteappdb.__main__ so that we can mock and test the module (docker in this case) without relying on subprocess.
Opening an issue for applying the same strategy for other tests outside the scope of #58.

Add support for validating docker image name in remoteappdb

---

remoteappmanager/application.py
remoteappmanager/db/csv_db.py
remoteappmanager/db/interfaces.py
remoteappmanager/handlers/home_handler.py
remoteappmanager/user.py
tests/test_application.py

Rename orm_user to account and document as opaque-type

---

remoteappmanager/cli/remoteappdb/__main__.py
remoteappmanager/db/orm.py
tests/cli/test_remoteappdb.py

Add foreign key support for sqlite

---

remoteappmanager/application.py
remoteappmanager/command_line_config.py
remoteappmanager/handlers/base_handler.py
remoteappmanager/handlers/home_handler.py
remoteappmanager/spawner.py
remoteappmanager/utils.py
tests/handlers/test_home_handler.py
tests/spawner/test_spawner.py
tests/test_command_line_config.py
tests/utils.py

Rename url to urlpath where it is possible and appropriate

---

remoteappmanager/db/csv_db.py
tests/db/abc_test_interfaces.py
tests/db/test_interfaces.py

Follows #80, mapping id containing '/' would cause problem with the rest api.
Added tests.

Ensure mapping id from CSVAccounting contains only hex characters

---

remoteappmanager/spawner.py

Fix #91 
This should be tested in jupyterhub, so we shouldn't need to test it (as we have not done).

Ensure config_file_path is configurable for Spawner

---

selenium_tests/selenium_test_base.py
selenium_tests/test_login_logout.py
selenium_tests/test_start_stop_container.py

Solving timeout problem and refactored tests

---

jupyterhub/remoteappmanager_config.py
remoteappmanager/file_config.py
tests/test_file_config.py

FileConfig consistency with dockerpy

---

selenium_tests/README.rst

Added README to selenium tests

---

doc/source/troubleshoot/docker.rst
doc/source/troubleshooting.rst

The message is unexpected, so it's good to have a reference for it.

Troubleshooting for potential timeout errors from incorrect docker configuration

---

doc/source/api/remoteappmanager.rst
doc/source/configuration.rst
jupyterhub/jupyterhub_config.py
remoteappmanager/spawners.py
remoteappmanager/tests/test_spawner.py
remoteappmanager/tests/test_spawners.py

Rename Spawner to SystemUserSpawner

---

remoteappmanager/handlers/home_handler.py

The current image info is now retrieved via REST and presented via javascript. There's no need to export a variable that is not used by the template.

Remove dead code now part of the REST API.

---

remoteappmanager/handlers/base_handler.py
remoteappmanager/handlers/handler_authenticator.py
remoteappmanager/handlers/tests/test_handler_authenticator.py

Extracted authenticator so that we can inject it in the REST handlers coming from tornado-rest, at the moment still not supporting this feature.

Extracting authenticator code to service REST handlers

---

Makefile

Current release of configurable-http-proxy has a bug that inverts the logic
of x-forward addition. This ruins the functionality of anything reverseproxied,
specifically the file transfer (which relies on these headers to produce the correct
urls)

Fixes xForward dependency.

---

requirements.txt
setup.py

Solves a conflict of versions between the current ubuntu deployment and the need for dockerpy. Pegged version for requests to 2.10.0

Fix requests version to 2.10.0

---

remoteappmanager/static/js/home.js
remoteappmanager/static/js/remoteappapi.js
remoteappmanager/static/js/utils.js

Skips the entries that err, for whatever reason, at the JS client level.
Fixes #221

Handle webapi requests failures

---

doc-requirements.txt
doc/source/index.rst

Adds requirements to fix readthedocs build. Adds the version to fix issue #187

Fix documentation on readthedocs

---

.gitignore
Makefile
jupyterhub/start.sh

Fixes #237.
Removes sudo in npm install so that we don't use the -g (global) option.

Remove sudo in npm install

---

.travis.yml
Makefile
doc/source/deployment.rst
doc/source/troubleshoot/docker.rst
requirements.txt
setup.py

Fixes the following: #239 #240 #238

Documentation and build update for Ubuntu 16.04 support.

---

Makefile
doc/source/deployment.rst

Provides documentation and a makefile rule to retrieve an up-to-date version of docker-engine from the docker apt sources.

Doc and makefile for Ubuntu14.04 updated docker engine.

---

Makefile

The test image for paraview is slowing down the tests for no real reason.

Use single image from hub docker: remove paraview.

---

remoteappmanager/docker/container_manager.py
remoteappmanager/docker/tests/test_container_manager.py

Adds the argument environment on ContainerManager.start_container, so that we can pass additional environment data.

Pass additional environment variables at container start

---

remoteappmanager/docker/docker_labels.py
remoteappmanager/docker/image.py
remoteappmanager/docker/tests/test_image.py
remoteappmanager/tests/mocking/virtual/docker_client.py

We need to differentiate image types (vnc, web) to decide which parameters to pass when creating them.

Export image type

---

remoteappmanager/docker/docker_labels.py
remoteappmanager/docker/image.py
remoteappmanager/docker/tests/test_image.py
remoteappmanager/tests/mocking/virtual/docker_client.py

Extracts the allowed environment variables declared by the image.

Extraction of allowed environment variables from labels.

---

remoteappmanager/docker/configurables.py
remoteappmanager/docker/image.py
remoteappmanager/docker/tests/test_configurables.py
remoteappmanager/docker/tests/test_image.py
remoteappmanager/restresources/application.py
remoteappmanager/restresources/container.py
remoteappmanager/restresources/tests/test_application.py
remoteappmanager/restresources/tests/test_container.py
remoteappmanager/tests/mocking/virtual/docker_client.py

Introduces configurables, design components that every image can export thanks to its specific envvar layout. This is the server side of the feature, which has been extracted and refactored from the more complicated server+ui.

Introduced configurables basic infrastructure. Server side handling

---

remoteappmanager/docker/configurables.py
remoteappmanager/docker/tests/test_configurables.py
remoteappmanager/restresources/container.py
remoteappmanager/restresources/tests/test_container.py

To support the command line client, we want configurable options to be optional.
If nothing is specified, the server will try to use a default, and if no default is present, it should act as in a bad representation.

Made configurables optional. Introduced default.

---

jstests/tests/home/mock_remoteappapi.js
jstests/tests/home/test_configurables.js
jstests/tests/home/test_models.js
jstests/tests/home/test_views.js
jstests/testsuite.js
remoteappmanager/static/js/home/configurables.js
remoteappmanager/static/js/home/home.js
remoteappmanager/static/js/home/models.js
remoteappmanager/static/js/home/views.js
remoteappmanager/static/js/remoteappapi.js

Introduces the client side manipulation and representation of the configurables provided server side.
For now implements the only configurable we have: resolution.

Configurables js client

---

Makefile
jstests/tests/test_remoteappapi.js
remoteappmanager/static/js/home/home.js
remoteappmanager/static/js/home/models.js
remoteappmanager/static/js/home/views.js
selenium_tests/selenium_test_base.py
selenium_tests/test_start_stop_container.py

Open new window when starting or viewing application

---

.gitignore

Hiding the new bower components directory, plus a few other files that are not relevant or generated.
Fixes part of #271

Hiding deployed/personalized files

---

remoteappmanager/cli/remoteapprest/__main__.py

Documented the behavior of start on an already started container.

---

CHANGES.rst
remoteappmanager/__init__.py

Release v0.8.0

---

remoteappmanager/docker/container.py
remoteappmanager/docker/container_manager.py
remoteappmanager/docker/docker_labels.py
remoteappmanager/docker/tests/test_container.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/restresources/container.py
remoteappmanager/tests/mocking/virtual/docker_client.py
remoteappmanager/utils.py

We need to store the urlpath where the container is, on the container itself. This is the only way we have for an administrative program to know which url to unregister when stopping someone else's container.
Alternative solutions involving changing the configurable http proxy have been debated 
https://github.com/jupyterhub/configurable-http-proxy/pull/87
https://github.com/jupyterhub/configurable-http-proxy/pull/88
and on gitter, and this PR is probably the most sensible strategy.

Assign absolute urlpath to the container.

---

remoteappmanager/cli/remoteappdb/__main__.py
remoteappmanager/db/csv_db.py
remoteappmanager/db/interfaces.py
remoteappmanager/db/orm.py
remoteappmanager/db/tests/test_orm.py

We need to have an id to refer to the accounting table, so that we can perform deletion without
issuing a query, and having an id to refer to via the webapi. The mapping id has done this since the beginning, but it's not in the table. Now it is.
This invalidates the database structure, so the 0.8.0 database will not be compatible.

Use mapping id  as a legitimate index to refer to the accounting table

---

requirements.txt
setup.py

Missing files require that we upgrade, again

Bumped tornado-webapi to 0.4.2

---

remoteappmanager/static/js/utils.js

Fixes a bug that made the request performed twice: jQuery .click() adds, rather than replace, the handler, resulting in multiple handlers being registered to the same event.

Fixes incorrect double addition of handler to dialogs when an error occurs

---

remoteappmanager/webapi/admin/accounting.py
remoteappmanager/webapi/admin/application.py
remoteappmanager/webapi/admin/tests/test_application.py
remoteappmanager/webapi/admin/tests/test_user.py
remoteappmanager/webapi/admin/user.py
remoteappmanager/webapi/container.py
remoteappmanager/webapi/tests/test_container.py
requirements.txt
setup.py

Changes against the latest version of tornado WebAPI (0.5.0.dev0)

Upgraded tornado-webapi and using its new api.

---

remoteappmanager/templates/admin/accounting.html
remoteappmanager/templates/admin/applications.html
remoteappmanager/templates/admin/containers.html
remoteappmanager/templates/admin/users.html
remoteappmanager/templates/macros.html
remoteappmanager/templates/page.html

Simple cleanup to have a separate file for macros.

Extracted macro to a separate file

---

remoteappmanager/static/js/remoteappapi.js

If the docker server is unavaiable for some reason, we want to stop the spinner anyway. We will get plenty of log on the server, but for now the user should not know.

Fixes forever stuck spinner in case of docker internal failure

---

doc/source/troubleshoot/general.rst
doc/source/troubleshooting.rst

"fix by doc" of issue #305 while I think of a better strategy.

Added a troubleshooting entry for issue #305

---

CHANGES.rst
remoteappmanager/handlers/admin/accounting_handler.py
remoteappmanager/handlers/admin/tests/test_admin_handlers.py
remoteappmanager/templates/admin/accounting.html
selenium_tests/IDE/admin_check_name_in_header_bug_348.html
selenium_tests/test_admin_name_header_bug.py

Fix incorrect username in admin interface

---

remoteappmanager/command_line_config.py
remoteappmanager/jupyterhub/tests/test_spawners.py
remoteappmanager/tests/test_command_line_config.py
remoteappmanager/tests/test_utils.py
remoteappmanager/tests/utils.py
remoteappmanager/utils.py
requirements.txt
setup.py

Upgrade jupyterhub to 0.7.2

---

remoteappmanager/jupyterhub/auth/github_whitelist_authenticator.py
requirements.txt
setup.py

Forced to update jupyterhub to master to address (again) #354 .
We are now running on jupyterhub development.
It also removes traitlets from the requirements, as it comes in with jupyterhub, and we need that version to be compatible with the rest.

Update to jupyterhub master.

---

remoteappmanager/jupyterhub/auth/github_whitelist_authenticator.py
remoteappmanager/jupyterhub/auth/tests/test_github_whitelist_authenticator.py

Addresses the following issues:
- adds config=True to allow the option to be set at config time.
- returns a copy of the set, because jupyterhub changes it.
- added mock setter to pacify jupyterhub.

Changes whitelist handling to cope with jupyterhub.

---

remoteappmanager/docker/container_manager.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/tests/mocking/dummy.py

There is no reason why the ContainerManager should export the docker client publicly.

Made the async docker client instance private

---

CHANGES.rst
jupyterhub/remoteappmanager_config.py
remoteappmanager/base_application.py
remoteappmanager/docker/container.py
remoteappmanager/docker/container_manager.py
remoteappmanager/docker/docker_labels.py
remoteappmanager/docker/tests/test_container.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/file_config.py
remoteappmanager/tests/mocking/virtual/docker_client.py
remoteappmanager/tests/test_file_config.py

Use container provenance information to prevent access to unrelated containers or simphony-remote instances

---

remoteappmanager/static/js/home/views/application_view.js
selenium_tests/selenium_test_base.py
selenium_tests/test_admin_name_header_bug.py
selenium_tests/test_start_stop_container.py

Fixes #347 
Will still not work for clicking on the canvas. Seems to be a limitation of the fact that canvas is inside an iframe, so it has no authority over controlling the focus.

Establish keyboard focus when the canvas is made visible

---

example_configs/jupyterhub-virtual-users-githubdauth_config.py
example_configs/jupyterhub-virtual-users-worldauth_config.py

Just two simple examples of configuration files

Added a few example configuration files

---

remoteappmanager/docker/container_manager.py
remoteappmanager/docker/tests/test_container_manager.py

Error when starting containers with rogue containers already present

---

jstests/tests/test_analytics.js
remoteappmanager/static/js/analytics.js
remoteappmanager/static/js/gamodule.js
remoteappmanager/static/js/home/controller.js
remoteappmanager/templates/page.html

Migrating and isolating google analytics to tolerate failure to load

---

remoteappmanager/cli/tests/test_remoteappdb.py
remoteappmanager/db/tests/test_csv_db.py
remoteappmanager/docker/container_manager.py
remoteappmanager/docker/tests/test_async_docker_client.py
remoteappmanager/docker/tests/test_configurables.py
remoteappmanager/docker/tests/test_container.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/docker/tests/test_image.py
remoteappmanager/handlers/admin/tests/test_admin_handlers.py
remoteappmanager/handlers/tests/test_base_handler.py
remoteappmanager/handlers/tests/test_home_handler.py
remoteappmanager/handlers/tests/test_register_container_handler.py
remoteappmanager/tests/mocking/dummy.py
remoteappmanager/tests/mocking/virtual/docker_client.py
remoteappmanager/tests/test_application.py
remoteappmanager/tests/test_command_line_config.py
remoteappmanager/tests/utils.py
remoteappmanager/webapi/admin/tests/test_accounting.py
remoteappmanager/webapi/admin/tests/test_application.py
remoteappmanager/webapi/admin/tests/test_container.py
remoteappmanager/webapi/admin/tests/test_user.py
remoteappmanager/webapi/container.py
remoteappmanager/webapi/tests/test_container.py

Refactoring of the Virtual Docker to make it more extensible.
Introduced the VirtualDockerClient to behave like a normal dockerpy client.
Disambiguated many confusing names, and followed a more consistent approach to ids.

Virtual docker cleanup

---

requirements.txt

Apparently something has changed upstream in jupyterhub so that it makes our master red.
I pinned against 2d1a45f0190059ef436c2f97dc8d6e391eb2d139 for now, but the problem needs to be investigated further.

Pinning against specific version of Jupyterhub to fix red.

---

Makefile
remoteappmanager/cli/tests/test_remoteappdb.py
remoteappmanager/db/tests/test_orm.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/handlers/admin/tests/test_admin_handlers.py
remoteappmanager/handlers/tests/test_base_handler.py
remoteappmanager/handlers/tests/test_home_handler.py
remoteappmanager/handlers/tests/test_register_container_handler.py
remoteappmanager/jupyterhub/auth/tests/test_github_whitelist_authenticator.py
remoteappmanager/jupyterhub/auth/tests/test_world_authenticator.py
remoteappmanager/jupyterhub/tests/test_spawners.py
remoteappmanager/services/tests/test_hub.py
remoteappmanager/services/tests/test_reverse_proxy.py
remoteappmanager/tests/mocking/virtual/docker_client.py
remoteappmanager/tests/test_application.py
remoteappmanager/tests/test_netutils.py
remoteappmanager/tests/test_utils.py

reduce clutter in the test by using LogTrapTestCase

Make tests less verbose.

---

jstests/tests/home/test_views.js
remoteappmanager/static/js/home/controller.js
remoteappmanager/static/js/home/models.js
remoteappmanager/static/js/home/views/application_list_view.js
remoteappmanager/static/js/home/views/application_view.js
remoteappmanager/static/js/utils.js
remoteappmanager/templates/home.html

Refactor model

---

CHANGES.rst
doc/source/configuration.rst
jupyterhub/remoteappmanager_config.py
remoteappmanager/base_application.py
remoteappmanager/cli/remoteappdb/__main__.py
remoteappmanager/db/csv_db.py
remoteappmanager/db/interfaces.py
remoteappmanager/db/orm.py
remoteappmanager/db/tests/abc_test_interfaces.py
remoteappmanager/db/tests/test_csv_db.py
remoteappmanager/db/tests/test_interfaces.py
remoteappmanager/db/tests/test_orm.py
remoteappmanager/file_config.py
remoteappmanager/handlers/admin/accounting_handler.py
remoteappmanager/handlers/tests/test_base_handler.py
remoteappmanager/tests/mocking/dummy.py
remoteappmanager/tests/test_application.py
remoteappmanager/tests/test_file_config.py
remoteappmanager/webapi/admin/tests/test_accounting.py
remoteappmanager/webapi/admin/tests/test_application.py
remoteappmanager/webapi/admin/tests/test_user.py
remoteappmanager/webapi/application.py
remoteappmanager/webapi/container.py
remoteappmanager/webapi/tests/test_application.py

The following changes have been introduced:
- The term Accounting now refers exclusively to the relationship table connecting users, applications and policies. 
- The config file `accounting_class` and `accounting_kwargs` are now `database_class` and `database_kwargs`.
- AppAccounting is now ORMDatabase. Similarly, CSVAccounting is now CSVDatabase.
The above two break compatibility with the old configuration files. As a result, it's important to bump the version to 2.0

Renamed some entities to more appropriate names

---

remoteappmanager/static/js/home/views/application_list_view.js
selenium_tests/test_hide_application.py

Deploys correct behavior for search, restricting to the applications that are relevant to the search itself.

Fix search form behavior

---

remoteappmanager/webapi/admin/application.py
remoteappmanager/webapi/admin/container.py
remoteappmanager/webapi/admin/tests/test_application.py
remoteappmanager/webapi/admin/tests/test_container.py
remoteappmanager/webapi/admin/tests/test_user.py
remoteappmanager/webapi/admin/user.py
requirements.txt

Changes to the server side admin webapi to support switch to Vue based interface.

Server side admin

---

remoteappmanager/static/js/home/views/application_list_view.js

Fix incompatibility issue with old browsers which does not support String's includes method (Opera and IE does not support it at all)

Fix incompatibility issue

---

jstests/helpers.js
jstests/tests/vue/components/test_ConfirmDialog.js
jstests/tests/vue/components/test_DataTable.js
jstests/testsuite.js
remoteappmanager/static/js/admin/main.js
remoteappmanager/static/js/admin/vue-components/toolkit/AdminLTEBox.js
remoteappmanager/static/js/admin/vue-components/toolkit/ConfirmDialog.js
remoteappmanager/static/js/admin/vue-components/toolkit/DataTable.js
remoteappmanager/static/js/admin/vue-components/toolkit/ModalDialog.js
remoteappmanager/static/js/admin/vue-components/toolkit/toolkit.js

Adds the following components:
- data-table: represents a table of data.
- confirm-dialog: a modal dialog to confirm or reject something
- modal-dialog: as before, but just put in toolkit now

Added toolkit of useful components

---

remoteappmanager/static/js/admin/vue-components/accounting/NewAccountingDialog.js
remoteappmanager/static/js/admin/vue-components/applications/NewApplicationDialog.js
remoteappmanager/static/js/admin/vue-components/users/NewUserDialog.js

We can use the trim modifier of Vue instead of the trim method of jQuery

Get rid of jQuery in the admin part

---

.jshintrc
remoteappmanager/static/js/admin/admin-resources.js
remoteappmanager/static/js/admin/main.js
remoteappmanager/static/js/admin/vue-components/AccountingView.js
remoteappmanager/static/js/admin/vue-components/ApplicationsView.js
remoteappmanager/static/js/admin/vue-components/ContainersView.js
remoteappmanager/static/js/admin/vue-components/MainView.js
remoteappmanager/static/js/admin/vue-components/UsersView.js
remoteappmanager/static/js/admin/vue-components/accounting/NewAccountingDialog.js
remoteappmanager/static/js/admin/vue-components/applications/NewApplicationDialog.js
remoteappmanager/static/js/admin/vue-components/users/NewUserDialog.js
remoteappmanager/static/js/gamodule.js
remoteappmanager/static/js/urlutils.js
remoteappmanager/static/js/user/configurables.js
remoteappmanager/static/js/user/main.js
remoteappmanager/static/js/user/models.js
remoteappmanager/static/js/user/user-resources.js
remoteappmanager/static/js/user/views/application_list_view.js
remoteappmanager/static/js/user/views/application_view.js
remoteappmanager/static/js/utils.js
remoteappmanager/static/js/vue/filters.js
remoteappmanager/static/js/vue/toolkit/AdminLTEBox.js
remoteappmanager/static/js/vue/toolkit/ConfirmDialog.js
remoteappmanager/static/js/vue/toolkit/DataTable.js
remoteappmanager/static/js/vue/toolkit/ModalDialog.js
remoteappmanager/static/js/vue/toolkit/toolkit.js

var -> let
prototype -> class definition
bind(this) -> arrow functions
indent 4 -> 2
#382

Add es6 features

---

frontend/user/vue-components/ApplicationView.vue

Fix issue when ApplicationView is not rendered because of an empty app list

---

frontend/user/ApplicationListModel.js
frontend/user/vue-components/ApplicationView.vue

In order to stay consistent with stopApplication method.
Closes #464

startApplication method now needs the index of the starting application

---

frontend/tests/tests/user/test_application_label.js
frontend/urlutils.js
frontend/user/vue-components/ApplicationLabel.vue
frontend/user/vue-components/ApplicationView.vue
frontend/vue/filters.js
package.json

When the user clicks on this share button, the application url is saved in the clipboard of the user and he can send this url to an other user

Add share button in the ApplicationLabel component

---

frontend/user/vue-components/ApplicationView.vue

Now it's written "Starting" on the disabled start button when the application is starting, and "Stopping" when the application is stopping.
This button was not disabled when stopping the application, now it is.
Workaround #477

Better feedback to user when starting and stopping application

---

frontend/tests/tests/test_analytics.js
frontend/tests/tests/user/mock_jsapi.js
frontend/tests/tests/user/test_application_view.js
frontend/tests/testsuite.js

There was a first side effect with mock_jsapi, it is used by almost all the tests but one test of the application view was changing it.
The second side effect was with the global object `window`, it was changed in the google analytics test.
Closes #470

Remove side effects in tests

---

frontend/tests/tests/test_analytics.js
frontend/tests/tests/user/mock_jsapi.js
frontend/tests/tests/user/test_application_view.js
frontend/tests/testsuite.js

Reverts simphony/simphony-remote#473
This PR apparently breaks the javascript tests. It is unclear why we didn't spot it in the build.

Revert "Remove side effects in tests"

---

bower.json
frontend/admin/vue-components/AccountingView.vue
frontend/admin/vue-components/ApplicationsView.vue
frontend/admin/vue-components/UsersView.vue
frontend/tests/tests/vue/components/test_DataTable.js
frontend/vue/toolkit/AdminLTEBox.vue
frontend/vue/toolkit/DataTable.vue
remoteappmanager/handlers/admin/tests/test_admin_handlers.py
remoteappmanager/templates/admin/page.html

We now use adminlte tables which are more responsive

Fix tables display issues

---

setup.py

Readthedocs does not have npm, so we can't run the full install there.

Handle readthedocs inability to run npm

---

frontend/tests/tests/user/test_application_label.js
frontend/tests/tests/user/test_application_view.js
frontend/user/vue-components/ApplicationLabel.vue
frontend/user/vue-components/ApplicationView.vue

As it's not a "button" element but a "li" element, there is no disable attribute, we only play with the disabled class which change the visual aspect but doesn't prevent the click event to be triggered.
I fixed this by changing the `disabled` class which now prevents the mouse events. 
Closes #479

Fix close button issue

---

doc-requirements.txt
setup.py

Python 3.5 generates an error in astor 0.5. We replace it with master and see if it works.

Use astor master to see if we fix the python3.5 compat

---

remoteappmanager/webapi/container.py
remoteappmanager/webapi/tests/test_container.py

The current webapi checks the accounting and fetches containers for the accounting data, but there was nothing to prevent operating on containers not active.

Skip containers that are not found while checking container.items

---

alembic.ini

Minor typo. We were missing a single slash

Fix typo in alembic config file

---

frontend/user/vue-components/ApplicationLabel.vue
frontend/user/vue-components/ApplicationView.vue
remoteappmanager/webapi/application.py
remoteappmanager/webapi/tests/test_application.py

As it's difficult to share the view of a web application, we disable the share link for those kind of applications.
I also added an information to the user about the type of the application.
Closes  #514

Disable share link when it's a web application

---

frontend/admin/vue-components/ContainersView.vue

Fix error when stopping a container from the admin interface

---

frontend/sharedDependencies.js
frontend/user/vue-components/ApplicationListView.vue
remoteappmanager/templates/page.html

When the user has a long list of applications we want a scrollbar for the application list. This is done in AdminLTE with the slimScroll plugin.

Add rendering support of a big application list

---

.travis.yml
Makefile
doc/source/deployment.rst
requirements.txt

Apparently something has changed at the docker apt repository, so the result is that the environment setup is compromised.

Fix build by renaming apt docker dependency

---

frontend/admin/admin-resources.js
frontend/user/user-resources.js

When copying files originally generated by the backend on the frontend, I didn't check the code. It turns out that the base_url was finally hard coded and no other user than "admin" and "test" could have access to data from the backend.
Closes #533

Fix issue with hard coded user name

---

Makefile
doc/source/deployment.rst
requirements.txt

Cherry-pick fb56ce3 to 4494f50 corresponding to the PR #529

Fix build 2.0

---

frontend/admin/vue-components/MainView.vue

Closes #532. I do not use a datatable component but a custom adminlte table

Improve the admin home view by using an adminlte box and table

---

frontend/user/vue-components/ApplicationView.vue

Add application logo to the start form

---

frontend/admin/vue-components/accounting/NewAccountingDialog.vue

I assume here that if it's a 404 error then it's because the image was not found.
Closes #507

Report fails due to invalid image name

---

.github/workflows/build_and_test.yml
.github/workflows/build_centos7.yml
.github/workflows/build_test_ubuntu18.yml
Makefile

Closes #557 
This PR adds a second workflow that targets CentOS 7, only installing Symphony Remote on this platform. Tests are run separately in the Ubuntu workflow.

Add build matrix with CentOS to GH Actions

---

doc/source/developer/docker.rst
frontend/user/vue-components/ApplicationView.vue
remoteappmanager/docker/configurables.py
remoteappmanager/docker/tests/test_configurables.py
remoteappmanager/tests/mocking/virtual/docker_client.py

Rename srdata configurable class tag to startupdata

---

remoteappmanager/cli/remoteapprest/__main__.py
remoteappmanager/cli/tests/test_remoteapprest.py

Closes #565 
The `remoteapprest app start` CLI command now accept a `--startupdata` option to provide a file path that will be loaded at startup. 
Note: the URL returned by the `remoteapprest app start` command cannot be used to open the container yet; there are two issues with it:
- the port referred in the URL is not correct
- the URL contains an extra `/api/v1/` that needs to be removed
The correct URL is the one printed in the logs; working on a way to return it through `remoteapprest`.

Extend remoteapprest to add startupdata option

---

remoteappmanager/cli/remoteapprest/__main__.py
remoteappmanager/cli/tests/test_remoteapprest.py
remoteappmanager/docker/container_manager.py

Closes #567 
[Includes changes from #566, changes will clean once that PR is merged]
Passing the right port to the response parsed by `remoteapprest app start` seems to be quite convoluted, so here is an approach which is a bit of a cheating, but it works and doesn't affect any other functionality. 
The container name is changed to include the right host port (e.g. "/simphony-remote_49165"), however this new name is not used internally (in fact it doesn't show in the logs); the container URL is still e.g. "http://127.0.0.1:49165/user/rpreste/containers/simphony-paraview/", because it is generated earlier in the process.
The new alternative URL is not functional, but it is sent in the response to the `remoteapprest app start` call, so it can then be parsed and rearranged to return the …

Return usable URL from remoteapprest app start

---

jupyterhub/remoteappmanager_config.py
remoteappmanager/base_application.py
remoteappmanager/file_config.py
remoteappmanager/tests/test_application.py
remoteappmanager/tests/test_user.py
remoteappmanager/user.py

Small fixes and enhancements required to allow a set of demo applications provided to all new users to be declared in the `jupyterhub/remoteappmanager_config.py` .
This is achieved by introducing two features:
- `FileConfig.demo_applications` can be configured with a list of image names that are already registered with the application
- `FileConfig.auto_user_creation` can be configured to allow automatic registration of any authenticated user. If set to `True`, as long as the user can login via the declared `c.JupyterHub.authenticator_class`, then an account will be automatically created in the Simphony-Remote database. Otherwise an admin user will have to manually perform the task
Examples of how these may be assigned are given in `jupyterhub/remoteappmanager_config.py`

Fix User demo application assignment

---

doc-requirements.txt

Add a version constraint to the docutils dependency to resolve problems with Sphinx.
Closes #574.

Add version constraint to the docutils dependency

---

README.rst

Discourage the use of Snap for installing Docker in the README, and hence close #572.
Update Docker installation URLs too

Discourage the use of Snap for installing Docker

---

.github/workflows/build_centos7.yml
.github/workflows/build_test_ubuntu18.yml

Run CI regularly twice a month to discover dependency issues (like #574) earlier. Currently they're arbitrarily scheduled for the 7th and 22nd days of the month.
From the documentation of [`on.schedule`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule):
> Scheduled workflows run on the latest commit on the default or base branch.
Closes #549

Run CI regularly twice a month

---

README.rst

Update the Readthedocs badge in `README.rst` to use HTTPS (rather than unencrypted HTTP).
Closes #548.

Update the Readthedocs badge in `README.rst`

---

.readthedocs.yaml
setup.py

Introduce an explicit config file for Readthedocs, `.readthedocs.yaml` and hence close #585.
Side effect: support for installing `remoteappmanager` using `python setup.py install` is removed. (See also #577 where it was originally introduced.)

Introduce Readthedocs config file

---

.github/workflows/trigger_doc_build.yml

Create a new scheduled GitHub action to trigger documentation builds on Readthedocs automatically. In addition to the builds initiated by PRs, this makes sure that the builds are run even if there is no development on this repo. With this changes to external dependencies will be discovered earlier and this will make it easier to maintain the documentation workflow in the future.
Closes #584.

Trigger Readthedocs builds regularly

---

requirements.txt
setup.py

Closes #599 
Applies a minimal solution of pinning `jinja2<3.1.0` when building on RTD and tidies up declaration of requirements between platforms.
In the long run we probably should be using later version of Sphinx on RTD, but this may require a larger number of changes.

Fix RTD build failures

---

doc/source/administration.rst
doc/source/configuration.rst
remoteappmanager/jupyterhub/auth/__init__.py
remoteappmanager/jupyterhub/auth/basic_authenticator.py
remoteappmanager/jupyterhub/auth/github_whitelist_authenticator.py
remoteappmanager/jupyterhub/auth/simphony_remote_auth_mixin.py
remoteappmanager/jupyterhub/auth/world_authenticator.py
remoteappmanager/jupyterhub/spawners.py
remoteappmanager/jupyterhub/tests/test_spawners.py
selenium_tests/AdminDriverTest.py
selenium_tests/RemoteAppDriverTest.py
selenium_tests/test_spawner_options_form.py

Closes #592
Makes use of JupyterHub's extendable spawner options form to provide admin users with the ability to spawn either "Admin" (`remoteappadmin`) or "User" (`remoteappmanager`) sessions when they login.
The existing session must be closed before the options form will be shown again. For JupyterHub < 1.0.0, the only way to do this is by navigating to `https://<simphony-remote>/hub/admin` or `https://<simphony-remote>/hub/home` whilst logged in and selecting the "Stop My Sever" option. 
Therefore (for now) we include the `SimphonyRemoteAuthMixin` class, providing a logout handler that automatically closes admin user servers upon a sign out. This has no effect on the functionality of the application since any Simphony-Remote applications will continue to run even if the JupyterHub …

Add Spawner options to enable admins to spawn user sessions

---

remoteappmanager/cli/remoteappdb/__main__.py
remoteappmanager/docker/async_docker_client.py
remoteappmanager/docker/container.py
remoteappmanager/tests/test_file_config.py
requirements.txt
setup.py

Approaches #449
Updates `docker-py` package 1.8 to `docker` 2.2 (name change from 2.x series onwards) but still uses the low-level API

Update `docker-py` 1.8 to `docker` 2.2

---

remoteappmanager/handlers/tests/test_base_handler.py
remoteappmanager/jupyterhub/auth/simphony_remote_auth_mixin.py
remoteappmanager/jupyterhub/spawners.py
remoteappmanager/jupyterhub/tests/test_spawners.py
requirements.txt
selenium_tests/AdminDriverTest.py
selenium_tests/UserDriverTest.py
selenium_tests/test_spawner_options_form.py
setup.py

Approaches #605
Upgrades the version of `jupyterhub` to latest in 0.9.x series (0.9.6).

Update `jupyterhub` to 0.9.x series

---

requirements.txt
setup.py

Targets https://github.com/simphony/simphony-remote/security/dependabot/1
Alternative to #547, including tidying up RTD deps
Have QC tested `requests==2.20.2` and `docker==2.2` running on Ubuntu 18.04 to confirm that both packages are compatible

Bump `requests` to 2.20.0
