remoteappmanager/handlers/home_handler.py

Mount a common data volume on the host machine to the container based on information given by the database.
Since we don't yet have a database, two namedtuples (Application and Volume) are coded here, and are to be placed by ORM objects.
Note: For docker version >= 1.11, mounting a host directory that does not exist will no longer create the directory (I was surprised to find out that it does for docker version < 1.11).  To be sure, we should always check if the source path exists.
I would prefer refactoring the path existence check to the ContainerManager._start_container in a separate PR.

Mount common volume for an application as read-only data volume

---

README.rst
doc/source/conf.py
readthedocs.yaml

Introduces the readthedocs yaml configuration. Apparently rtd does not support pull request building, so I will probably self-merge and check if the docs are correctly rebuilt.

Added readthedocs yaml file.

---

remoteappmanager/__main__.py
remoteappmanager/application.py
remoteappmanager/application_config.py
remoteappmanager/handlers/base_handler.py
remoteappmanager/handlers/home_handler.py
remoteappmanager/utils.py

Fix #24 
Should be revisited after #25

HomeHandler.get and post requires authentication

---

remoteappmanager/__init__.py

Bumped version to 0.3.0

---

remoteappmanager/cli/remoteappdb/__main__.py
requirements.txt
tests/cli/test_remoteappdb.py

Provides an enhanced version of the remoteappdb that allows removal of users and apps, and better error report.

Enhanced remoteappdb

---

doc/source/api/remoteappmanager.db.rst
remoteappmanager/application.py
remoteappmanager/db/csv_db.py
tests/db/test_csv_db.py
tests/test_application.py

Feature csv database interface

---

remoteappmanager/spawner.py

Log nicer error message when VirtualUserSpawner.workspace_dir is not writeable

---

Makefile
remoteappmanager/cli/remoteappdb/__main__.py
scripts/generate_certificate.sh

Makefile for basic deployment operations

---

remoteappmanager/docker/image.py
tests/docker/test_container_manager.py
tests/docker/test_image.py
tests/utils.py

Fix loading docker image labels

---

remoteappmanager/handlers/base_handler.py
remoteappmanager/services/hub.py
tests/handlers/test_home_handler.py
tests/services/test_hub.py
tests/utils.py

Asynchronous verification of the user.

---

jupyterhub/remoteappmanager_config.py
remoteappmanager/spawner.py
tests/spawner/test_spawner.py

Fixes lack of docker environment due to change in HOME dir
and associated incorrect configuration/spawning of the singleuserapp.

Fixes lack of docker environment.

---

jupyterhub/remoteappmanager_config.py
remoteappmanager/application.py
remoteappmanager/file_config.py
tests/fixtures/remoteappmanager_config.py
tests/handlers/test_home_handler.py
tests/test_application.py
tests/test_file_config.py
tests/utils.py

Support arbitrary database implementation

---

tests/spawner/test_spawner.py

TestSpawner uses ioloop and should use tornado.testing.AsyncTestCase
Fix #60

Fix ResourceWarning in tests

---

remoteappmanager/docker/container_manager.py
remoteappmanager/handlers/home_handler.py
remoteappmanager/templates/home.html
tests/docker/test_container_manager.py
tests/handlers/test_home_handler.py

Fixes #100
Fixes #101 as a corollary

Fix problem with OSX and View button

---

remoteappmanager/db/orm.py
tests/db/test_orm.py

Fix #71 
Will likely have mini merge conflicts with #94 on imports.

Make sqlite database session and transaction have the same scope

---

remoteappmanager/docker/container.py
tests/docker/test_container.py
tests/docker/test_container_manager.py

Make sure container public port value is not None

---

doc/source/design.rst

Not sure if I want to modify the binary png image just for this.

Documentation notes on HTTP connection to docker

---

doc/source/index.rst
doc/source/utilities.rst
remoteappmanager/cli/remoteappdb/__main__.py

Documents the two CLI commands remoteapprest and remoteappdb

Added documentation for the CLI commands

---

remoteappmanager/restresources/container.py
tests/restmodel/test_container.py

Fix for incorrect variable name url/urlpath

---

remoteappmanager/application.py
remoteappmanager/handlers/home_handler.py
remoteappmanager/restresources/container.py
remoteappmanager/services/reverse_proxy.py
tests/handlers/test_home_handler.py
tests/mock/mock_reverse_proxy.py
tests/restmodel/test_container.py
tests/services/test_reverse_proxy.py

Brought the interface of the reverse proxy to its level of abstraction, removing methods concerning the container.
Fixes #114

Reverse proxy remove of container specific methods.

---

remoteappmanager/handlers/home_handler.py
tests/handlers/test_home_handler.py

Removed finish from subhandlers

---

remoteappmanager/cli/remoteappdb/__main__.py

Added description to remoteappdb cli.

---

remoteappmanager/file_config.py
tests/test_file_config.py

Do not override previous defaults with file parsing

---

remoteappmanager/db/orm.py
tests/db/test_interfaces.py
tests/db/test_orm.py

Ensure no empty file created if target sqlite database does not exist

---

remoteappmanager/file_config.py
tests/test_file_config.py

Fix for incorrect auto placement in Client initialization

---

tests/mocking/virtual/docker_client.py

This is causing a lot of PRs red

Fix flake8

---

COPYING.rst
README.rst
doc/source/index.rst
doc/source/license.rst

Adding license in readme

---

remoteappmanager/file_config.py

Documented DOCKER_TLS_VERIFY behavior

---

doc/source/deployment.rst

Change directory in documentation

---

MANIFEST.in

Added jupyter_config.py file to manifest

---

remoteappmanager/tests/test_spawners.py

Removes start/stop spawner

---

.travis.yml
Makefile
remoteappmanager/spawners.py
requirements.txt
setup.py

Moving to 0.7.0dev0 as we need to add the patch for redirection.

Upgrading to jupyterhub development

---

remoteappmanager/restresources/application.py
remoteappmanager/restresources/tests/test_application.py

Server side exclude application if no longer available.

---

remoteappmanager/cli/remoteapprest/__main__.py
remoteappmanager/cli/tests/test_remoteapprest.py

Basic information on inquire: just the UI name

---

doc/source/_extensions/__init__.py
doc/source/conf.py
doc/source/developer.rst
doc/source/mock_missing.py
setup.py

Some modules not working on RTD due to lack of appropriate dependency modules after eviction of docker and jupyterhub.
Also, removed reference to the REST documentation, as it will be part of a separate module, and it's for all practical purposes deprecated.

Fix autosummary inability to find some modules. Removed obsolete documentation.

---

remoteappmanager/restresources/application.py
remoteappmanager/restresources/tests/test_application.py
remoteappmanager/static/js/home.js

Shows the policies in the application list.

Show policies

---

CHANGES.rst
remoteappmanager/__init__.py

Version 0.7.0 changelog and version pinning.

---

remoteappmanager/static/js/home/views.js

Added spinner and No apps found message

---

remoteappmanager/handlers/tests/test_home_handler.py
remoteappmanager/static/css/remoteappmanager.css
remoteappmanager/templates/home.html
remoteappmanager/templates/page.html
selenium_tests/test_login_logout.py

Minor changes in style for a more pleasant aspect of the application list.

Minor changes in style

---

.travis.yml

Allows for nicer display of the report on travis.

Moved the installation of devdeps to before_script.

---

remoteappmanager/spawners.py
remoteappmanager/tests/test_spawners.py

Workspace is now created with a defined username and preserved.
Fixes #261

Change of strategy with workspace.

---

bower.json
jstests/tests.html
jstests/tests/home/mock_remoteappapi.js
jstests/tests/home/test_configurables.js
jstests/tests/home/test_models.js
jstests/tests/home/test_views.js
jstests/tests/test_remoteappapi.js
jstests/tests/test_utils.js
jstests/testsuite.js

Blanket JS coverage

---

doc/source/developer.rst
doc/source/developer/docker.rst

Documentation for docker protocol

---

remoteappmanager/cli/remoteapprest/__main__.py
remoteappmanager/docker/container_manager.py
remoteappmanager/docker/tests/test_container_manager.py

Fixes return strategy in case of double request. Now raises an exception (which is correctly handled at the webapi level) instead of returning None

Introduced error in case of double request.

---

remoteappmanager/__init__.py

Increments the release to 0.9.0.dev0

post v0.8.0

---

remoteappmanager/static/js/home/views.js

Eye candy for application show.

Added fading in effect to application addition

---

doc-requirements.txt
requirements.txt

Pinned requirements to specific versions

Pinned requirements

---

CHANGES.rst
Makefile
doc/source/utilities.rst
remoteappmanager/cli/remoteappdb/__main__.py
remoteappmanager/cli/tests/test_remoteappdb.py

Accepting database as argument instead of option.

---

remoteappmanager/docker/container.py
remoteappmanager/docker/container_manager.py
remoteappmanager/docker/docker_labels.py
remoteappmanager/docker/image.py
remoteappmanager/docker/tests/test_container.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/docker/tests/test_image.py
remoteappmanager/tests/mocking/virtual/docker_client.py

New label namespace for runtime information

---

remoteappmanager/__main__.py
remoteappmanager/application.py
remoteappmanager/environment_config.py
remoteappmanager/handlers/tests/test_base_handler.py
remoteappmanager/handlers/tests/test_home_handler.py
remoteappmanager/restresources/tests/test_container.py
remoteappmanager/services/hub.py
remoteappmanager/services/reverse_proxy.py
remoteappmanager/services/tests/test_hub.py
remoteappmanager/services/tests/test_reverse_proxy.py
remoteappmanager/tests/mocking/dummy.py
remoteappmanager/tests/test_application.py
remoteappmanager/tests/test_environment_config.py
remoteappmanager/tests/utils.py

Removed setting of PROXY_API_TOKEN

---

remoteappmanager/restresources/application.py
remoteappmanager/restresources/container.py
remoteappmanager/restresources/decorators.py

Extraction of validation of the user by the resource methods

Introducing authenticator decorator for cleaner guarding

---

remoteappmanager/application.py
remoteappmanager/base_application.py
remoteappmanager/tests/test_application.py

Extract base application as a preparation to provide an administrative application.

Extract Base application

---

remoteappmanager/docker/container.py
remoteappmanager/docker/tests/test_container.py
remoteappmanager/docker/tests/test_container_manager.py
remoteappmanager/tests/utils.py

Added extraction of the user to the container.

Container: add user to the traitlets

---

remoteappmanager/db/csv_db.py
remoteappmanager/db/exceptions.py
remoteappmanager/db/interfaces.py
remoteappmanager/db/orm.py
remoteappmanager/db/tests/abc_test_interfaces.py
remoteappmanager/db/tests/test_csv_db.py
remoteappmanager/db/tests/test_interfaces.py
remoteappmanager/db/tests/test_orm.py
remoteappmanager/tests/mocking/dummy.py
remoteappmanager/tests/test_utils.py
remoteappmanager/utils.py

Extends accounting to allow retrieve/create operations on users, applications, and permission granting.

Extended accounting

---

remoteappmanager/base_application.py
remoteappmanager/db/csv_db.py
remoteappmanager/db/interfaces.py
remoteappmanager/db/orm.py
remoteappmanager/db/tests/abc_test_interfaces.py
remoteappmanager/db/tests/test_csv_db.py
remoteappmanager/db/tests/test_interfaces.py
remoteappmanager/db/tests/test_orm.py
remoteappmanager/tests/mocking/dummy.py
remoteappmanager/utils.py

Retrieve the user via id, in addition to name.

Get user via id

---

remoteappmanager/handlers/admin/applications_handler.py
remoteappmanager/handlers/admin/containers_handler.py
remoteappmanager/handlers/admin/user_applications_handler.py
remoteappmanager/handlers/admin/users_handler.py
remoteappmanager/templates/admin/page.html

UI style. Adds tabs to the admin interface.

Added tab navs style for admin interface

---

requirements.txt
setup.py

Upgraded tornado webapi to 0.3.0

Updated tornado-webapi package

---

remoteappmanager/admin_application.py
remoteappmanager/handlers/admin/applications_handler.py
remoteappmanager/restresources/admin/__init__.py
remoteappmanager/restresources/admin/application.py
remoteappmanager/restresources/admin/tests/test_application.py
remoteappmanager/static/css/remoteappmanager.css
remoteappmanager/static/js/admin/adminapi.js
remoteappmanager/static/js/admin/applications/controller.js
remoteappmanager/static/js/admin/containers/controller.js
remoteappmanager/static/js/utils.js
remoteappmanager/templates/admin/applications.html
remoteappmanager/templates/page.html
remoteappmanager/tests/mocking/dummy.py

Provides functionaly to create and delete applications from the web interface.

Delete and create Applications

---

remoteappmanager/static/js/admin/applications/controller.js
remoteappmanager/static/js/admin/containers/controller.js
remoteappmanager/static/js/admin/home/controller.js
remoteappmanager/static/js/home/configurables.js
remoteappmanager/static/js/home/models.js
remoteappmanager/static/js/home/views.js
remoteappmanager/static/js/utils.js

Minor cleanups on the code layout.

Cleanup of some cruft and improper formatting in javascript files

---

remoteappmanager/handlers/admin/admin_home_handler.py
remoteappmanager/static/css/remoteappmanager.css
remoteappmanager/templates/admin/applications.html
remoteappmanager/templates/admin/containers.html
remoteappmanager/templates/admin/home.html
remoteappmanager/templates/admin/page.html
remoteappmanager/templates/admin/tabular.html

Minor restyling to provide a better welcoming once logged in.

Restyling of the admin home page

---

remoteappmanager/tests/webapi_test_case.py
remoteappmanager/webapi/admin/tests/test_application.py
remoteappmanager/webapi/admin/tests/test_container.py
remoteappmanager/webapi/admin/tests/test_user.py
remoteappmanager/webapi/tests/test_application.py
remoteappmanager/webapi/tests/test_container.py

Simple cleanup of the tests for resources.

WebAPI test case

---

doc/source/administration.rst
doc/source/configuration.rst
doc/source/index.rst
doc/source/utilities.rst

Provides information about the administrative interface.

Administration documentation

---

remoteappmanager/static/js/admin/accounting/controller.js

Fixes the incorrect value to define the volume.

Fixed typo in representation variables

---

requirements.txt
setup.py

Upgrade to tornado-webapi 0.4.0

Upgraded tornadowebapi to 0.4.0

---

remoteappmanager/templates/admin/accounting.html
remoteappmanager/templates/admin/applications.html
remoteappmanager/templates/admin/containers.html
remoteappmanager/templates/admin/users.html

Makes the table nicer before it gets decorated via javascript

Fixed table aspect by setting class

---

jstests/tests/test_urlutils.js
jstests/tests/test_utils.js
remoteappmanager/static/js/admin/accounting/controller.js
remoteappmanager/static/js/admin/applications/controller.js
remoteappmanager/static/js/admin/containers/controller.js
remoteappmanager/static/js/admin/users/controller.js
remoteappmanager/static/js/dialogs.js
remoteappmanager/static/js/home/controller.js
remoteappmanager/static/js/home/views.js
remoteappmanager/static/js/remoteappapi.js
remoteappmanager/static/js/urlutils.js
remoteappmanager/static/js/utils.js

Cleaning utils module:
- removed code that was used in jupyterhub but it's not used by us.
- Split the module in three: urlutils, utils, and dialogs.

Clean utils module

---

doc/source/mock_missing.py
remoteappmanager/__init__.py
remoteappmanager/docker/docker_labels.py
setup.py

Merged changes for version 1.0 into master.

Merge v1.0

---

Makefile

Fixes changes in dependencies from ubuntu trusty since the last build.

Fix deps build

---

setup.py

Removed selenium_tests package from deployment

---

remoteappmanager/jupyterhub/auth/github_whitelist_authenticator.py
remoteappmanager/jupyterhub/auth/tests/test_github_whitelist_authenticator.py

Skipping lines starting with "#" in the whitelist file.

Skipping comments in whitelist file

---

CHANGES.rst
setup.py

Release branch for version 1.1.0

Release 1.1.0

---

package.json

Upgraded configurable-http-proxy to 2.0.1

---

remoteappmanager/handlers/admin/admin_home_handler.py
remoteappmanager/templates/admin/home.html

Added better statistics in the main admin panel

---

jupyterhub/jupyterhub_config.py

Introduces a small change in the configuration so that we can run when there's only loopback.

Allows running when there is no internet.

---

Makefile

Reducing the verbosity of the build as the log becomes too long for convenient browsing.

Reducing verbosity at build

---

frontend/admin/vue-components/AccountingView.vue
frontend/admin/vue-components/ApplicationsView.vue
frontend/admin/vue-components/ContainersView.vue
frontend/admin/vue-components/UsersView.vue
frontend/admin/vue-components/accounting/NewAccountingDialog.vue
frontend/admin/vue-components/applications/NewApplicationDialog.vue

Replace show attribute to visible

---

CHANGES.rst
setup.py

Release branch for version 2.0

Release 2.0.0

---

CHANGES.rst
setup.py

Bump version to 2.1.0.dev0

---

frontend/user/vue-components/ApplicationLabel.vue

HTML input elements are not supposed to be closed https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input

HTML input elements are not supposed to be closed

---

frontend/admin/admin-resources.js
frontend/user/user-resources.js

Fix issue with the user name

---

.github/workflows/trigger_doc_build.yml

Clean up `trigger_doc_build.yml` following PR #588

Clean up `trigger_doc_build.yml`

---

CHANGES.rst
setup.py

Release PR for the 2.2.0 version

Release 2.2.0
